#!/bin/bash
# FoxDen greeter art
# Usage: source ~/dotfiles/surface/art1
#        or: bash ~/dotfiles/surface/art1

Y=$'\e[1;33m'  # yellow - cat
G=$'\e[1;32m'  # green  - japanese
B=$'\e[1;34m'  # blue   - message box
R=$'\e[m'      # reset

printf "%s%s%s%s%s%s%s\n" "$Y" $'Zzzzz  |\\      _,,,--,,_     ' "$G" $'何おシ' "$B" $'+-----------------------------+' "$R"
printf "%s%s%s%s%s%s%s\n" "$Y" $'       /,`.-\'`\'   ._  \\-;;,_ ' "$G" $'をかス' "$B" $'| Why is there always a cat   |' "$R"
printf "%s%s%s%s%s%s%s\n" "$Y" $'      |,4-  ) )_   .;.(  `\'-\'' "$G" $'しえテ' "$B" $'| on whatever you\'re editing? |' "$R"
printf "%s%s%s%s%s%s%s\n" "$Y" $'     \'---\'\'(_/._)-\'(_\\_)     ' "$G" $'たりム' "$B" $'+-----------------------------+' "$R"
printf "%s%s%s\n" "$G" $'                             い  ス' "$R"
printf "%s%s%s\n" "$G" $'                             で  タ' "$R"
printf "%s%s%s\n" "$G" $'                             す  |' "$R"
printf "%s%s%s\n" "$G" $'                             か  ト' "$R"
